services:
  - type: web
    name: codeforge-ide
    env: node
    plan: free
    buildCommand: npm install && node package-patch.js && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
      - key: GITHUB_REPOSITORY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html